## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
#urlDB: jdbc:mysql://db4free.net:3307/clasesdaw?useSSL=false
#userDB: oscarnovillo
#passDB: c557ef
urlDB: jdbc:mysql://localhost:3306/clasesdaw
userDB: root
passDB: root
mailFrom: tiendaonlinemiguel@gmail.com
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: 123456abcd

##passDB: clasesdaw