## YAML Template.
---
driverDB: com.mysql.jdbc.Driver
urlDB: jdbc:mysql://localhost:3306/clasesdaw
## urlDB: jdbc:mysql://localhost:3306/clasesdaw?useSSL=false
userDB: root
passDB: nohay2sin3
mailFrom: alumno1@iesquevedo.es
smtpServer: smtp.gmail.com
smtpPort: 587
mailPass: alumnodam2

##passDB: clasesdaw